apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.11.3
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
        - name: elasticsearch-data
          emptyDir: {}
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.5"


# apiVersion: elasticsearch.k8s.elastic.co/v1
# kind: Elasticsearch
# metadata:
#   name: quickstart
# spec:
#   version: 8.11.3
#   nodeSets:
#   - name: default
#     count: 1
#     config:
#       node.store.allow_mmap: false
#     podTemplate:
#       spec:
#         containers:
#         - name: elasticsearch
#           resources:
#             requests:
#               memory: "2Gi"
#               cpu: "0.5"
#     volumeClaimTemplates:
#     - metadata:
#         name: elasticsearch-data
#       spec:
#         accessModes:
#         - ReadWriteOnce
#         resources:
#           requests:
#             storage: 5Gi
